services:
  android-emulator:
    image: budtmo/docker-android:emulator_11.0
    privileged: true
    ports:
      - "6080:6080"   # noVNC — xem màn hình emulator
      - "5554:5554"
      - "5555:5555"   # ADB
    environment:
      EMULATOR_DEVICE: Samsung Galaxy S10
      WEB_VNC: "true"
    devices:
      - /dev/kvm:/dev/kvm
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
