import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:printing/printing.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfPreviewService {
  /// Generate PDF data for preview
  static Future<Uint8List> generateReportPreview({
    required String userDisplayName,
    required String reportTitle,
    required Map<String, dynamic> analyticsData,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            pw.Container(
              padding: const pw.EdgeInsets.only(bottom: 20),
              decoration: const pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(color: PdfColors.blue800, width: 2),
                ),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'IT Research Analytics Report',
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.blue800,
                    ),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    reportTitle,
                    style: pw.TextStyle(
                      fontSize: 18,
                      color: PdfColors.grey700,
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'Generated by: $userDisplayName',
                    style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                  ),
                  pw.Text(
                    'Date: ${DateTime.now().toString().split(' ')[0]}',
                    style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 30),

            // Executive Summary
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.blue50,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Executive Summary',
                    style: pw.TextStyle(
                      fontSize: 16,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.blue800,
                    ),
                  ),
                  pw.SizedBox(height: 10),
                  pw.Text(
                    'This report provides comprehensive analytics on IT research trends, focusing on key areas including Machine Learning, Artificial Intelligence, Cybersecurity, and emerging technologies. The analysis covers publication trends, author contributions, and research impact metrics.',
                    style: const pw.TextStyle(fontSize: 11, height: 1.4),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // Key Metrics Section
            pw.Text(
              'Key Research Metrics',
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue800,
              ),
            ),
            pw.SizedBox(height: 10),

            // Metrics Table
            pw.TableHelper.fromTextArray(
              context: context,
              data: [
                ['Metric', 'Value', 'Description'],
                ['Total Publications', analyticsData['totalPublications'] ?? '156', 'IT-focused research papers'],
                ['Active Researchers', analyticsData['activeResearchers'] ?? '89', 'Contributors in the field'],
                ['Top Conferences', analyticsData['topConferences'] ?? '24', 'Leading IT conferences'],
                ['Average Citations', analyticsData['avgCitations'] ?? '15.3', 'Per publication impact'],
                ['Research Period', analyticsData['researchPeriod'] ?? '2020-2024', 'Analysis timeframe'],
              ],
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.blue800,
              ),
              cellStyle: const pw.TextStyle(fontSize: 10),
              cellPadding: const pw.EdgeInsets.all(8),
              oddRowDecoration: const pw.BoxDecoration(
                color: PdfColors.grey100,
              ),
            ),

            pw.SizedBox(height: 20),

            // Research Areas
            pw.Text(
              'Top Research Areas',
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue800,
              ),
            ),
            pw.SizedBox(height: 10),

            pw.Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                'Machine Learning',
                'Artificial Intelligence',
                'Cybersecurity',
                'Blockchain',
                'Cloud Computing',
                'IoT',
                'Big Data Analytics',
                'Computer Vision',
                'Natural Language Processing',
                'Software Engineering',
              ].map((area) => pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue100,
                  borderRadius: pw.BorderRadius.circular(12),
                ),
                child: pw.Text(
                  area,
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.blue800),
                ),
              )).toList(),
            ),

            pw.SizedBox(height: 20),

            // Trends Analysis
            pw.Text(
              'Research Trends Analysis',
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue800,
              ),
            ),
            pw.SizedBox(height: 10),

            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Bullet(text: 'AI/ML research shows 24% growth year-over-year'),
                pw.Bullet(text: 'Cybersecurity publications increased by 18% in 2024'),
                pw.Bullet(text: 'Blockchain technology research stabilizing at mature levels'),
                pw.Bullet(text: 'Edge Computing emerging as a key research area'),
                pw.Bullet(text: 'Quantum Computing research gaining momentum'),
              ],
            ),

            pw.SizedBox(height: 20),

            // Geographic Distribution
            pw.Text(
              'Geographic Distribution',
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue800,
              ),
            ),
            pw.SizedBox(height: 10),

            pw.TableHelper.fromTextArray(
              context: context,
              data: [
                ['Country/Region', 'Publications', 'Share (%)'],
                ['United States', '2,847', '35%'],
                ['China', '2,278', '28%'],
                ['United Kingdom', '976', '12%'],
                ['Germany', '651', '8%'],
                ['Canada', '488', '6%'],
                ['Others', '895', '11%'],
              ],
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.blue800,
              ),
              cellStyle: const pw.TextStyle(fontSize: 10),
              cellPadding: const pw.EdgeInsets.all(8),
              oddRowDecoration: const pw.BoxDecoration(
                color: PdfColors.grey100,
              ),
            ),

            pw.SizedBox(height: 30),

            // Footer
            pw.Container(
              padding: const pw.EdgeInsets.only(top: 20),
              decoration: const pw.BoxDecoration(
                border: pw.Border(
                  top: pw.BorderSide(color: PdfColors.grey300, width: 1),
                ),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Report Generated by Journal Trend Analyzer',
                    style: pw.TextStyle(
                      fontSize: 12,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.blue800,
                    ),
                  ),
                  pw.Text(
                    'Powered by OpenAlex API & Firebase Analytics',
                    style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                  ),
                  pw.Text(
                    'For more information, visit our research dashboard.',
                    style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                  ),
                ],
              ),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  /// Show PDF preview in a dialog
  static Future<void> showPdfPreview(
    BuildContext context, {
    required String userDisplayName,
    required String reportTitle,
    required Map<String, dynamic> analyticsData,
  }) async {
    await showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => Dialog(
        insetPadding: const EdgeInsets.all(16),
        child: Container(
          height: MediaQuery.of(context).size.height * 0.9,
          width: MediaQuery.of(context).size.width * 0.95,
          child: Column(
            children: [
              // Header
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Theme.of(context).primaryColor,
                  borderRadius: const BorderRadius.vertical(
                    top: Radius.circular(12),
                  ),
                ),
                child: Row(
                  children: [
                    Icon(
                      Icons.picture_as_pdf,
                      color: Colors.white,
                      size: 20,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'Preview Report: $reportTitle',
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                    IconButton(
                      onPressed: () => Navigator.of(context).pop(),
                      icon: const Icon(Icons.close, color: Colors.white),
                    ),
                  ],
                ),
              ),
              // PDF Preview
              Expanded(
                child: PdfPreview(
                  build: (format) => generateReportPreview(
                    userDisplayName: userDisplayName,
                    reportTitle: reportTitle,
                    analyticsData: analyticsData,
                  ),
                  allowPrinting: true,
                  allowSharing: true,
                  canChangePageFormat: false,
                  canDebug: false,
                  actions: [
                    // Custom action buttons
                    PdfPreviewAction(
                      icon: const Icon(Icons.save_alt),
                      onPressed: (context, build, pageFormat) async {
                        // This will trigger the save/share functionality
                        final pdfData = await build(pageFormat);
                        Navigator.of(context).pop(pdfData);
                      },
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}